# Generated by Django 2.2.3 on 2019-07-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0002_bpmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=10, verbose_name='任务状态')),
                ('bot_number', models.IntegerField(verbose_name='Bot编号')),
                ('user_location', models.URLField(verbose_name='用户路径')),
                ('created_time', models.DateTimeField(verbose_name='BOT创建时间')),
            ],
            options={
                'verbose_name': 'BOT',
                'verbose_name_plural': 'BOT',
            },
        ),
        migrations.AlterModelOptions(
            name='bpmission',
            options={'verbose_name': 'BP记录', 'verbose_name_plural': 'BP记录'},
        ),
    ]
