# Generated by Django 2.2.3 on 2019-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0005_auto_20190721_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bypass',
            name='bot_name',
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(max_length=10, null=True, verbose_name='机器人类型'),
        ),
        migrations.AddField(
            model_name='bypass',
            name='bot_type',
            field=models.CharField(max_length=10, null=True, verbose_name='机器人类型'),
        ),
        migrations.AddField(
            model_name='fogbot',
            name='bot_type',
            field=models.CharField(max_length=10, null=True, verbose_name='机器人类型'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_site',
            field=models.CharField(max_length=10, null=True, verbose_name='商品站名'),
        ),
        migrations.AddField(
            model_name='task',
            name='bot_type',
            field=models.CharField(max_length=10, null=True, verbose_name='机器人类型'),
        ),
    ]
