# Generated by Django 2.2.3 on 2019-07-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0006_auto_20190721_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_provider', models.CharField(max_length=10, null=True, verbose_name='供应商')),
                ('proxy_id', models.CharField(max_length=3, null=True, verbose_name='代理编号')),
                ('proxy_ip', models.CharField(max_length=10, verbose_name='代理地址')),
                ('proxy_port', models.IntegerField(verbose_name='代理端口')),
                ('proxy_usr', models.CharField(max_length=10, null=True, verbose_name='代理账号')),
                ('proxy_psw', models.IntegerField(max_length=20, null=True, verbose_name='代理密码')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_variants',
            field=models.CharField(max_length=200, null=True, verbose_name='库存信息'),
        ),
    ]
