# Generated by Django 2.2.3 on 2019-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0007_auto_20190721_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxies',
            name='proxy_ip',
            field=models.CharField(max_length=20, verbose_name='代理地址'),
        ),
        migrations.AlterField(
            model_name='proxies',
            name='proxy_port',
            field=models.IntegerField(max_length=5, verbose_name='代理端口'),
        ),
        migrations.AlterField(
            model_name='proxies',
            name='proxy_provider',
            field=models.CharField(max_length=20, null=True, verbose_name='供应商'),
        ),
    ]
