# Generated by Django 2.2.3 on 2019-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0009_auto_20190723_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBypass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_type', models.CharField(max_length=20, null=True, verbose_name='自动BP类型')),
                ('is_on', models.BooleanField(default=False, verbose_name='开启状态')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='BOT创建时间'),
        ),
        migrations.AlterField(
            model_name='fogbot',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='BOT创建时间'),
        ),
    ]
